[ARC-1965] Create Layouts
AleksandreGalogreBaramidze/OChat pull request #1
Opened 2021-12-21 10:24 UTC by AleksandreGalogreBaramidze

https://spaceneobank.atlassian.net/browse/ARC-1965

2021-12-21 10:31 UTC, AnaRusadze requested changes

2021-12-21 10:31 UTC, AnaRusadze commented on app/src/main/java/com/example/chat/ZezvaFragment.kt
> +class ZezvaFragment : Fragment() {
zezva fragment...
really?

2021-12-21 10:31 UTC, AnaRusadze commented on app/src/main/res/drawable/other_user_message.xml
> +        android:endColor="#475D8C"
ფერების რესურსებში გატანა ჯობია

2021-12-21 10:31 UTC, AnaRusadze commented on app/src/main/res/layout/other_user_message_layout.xml
> +            tools:text="მზია მზია მზია"
ctrl alt l

2021-12-21 10:31 UTC, AnaRusadze commented on app/src/main/res/layout/other_user_message_layout.xml
> +<androidx.appcompat.widget.LinearLayoutCompat xmlns:android="http://schemas.android.com/apk/res/android"
.LinearLayoutCompat ეს რუთი რისთვის გჭირდება, პირდაპირ კონსტრეინტში ჩასვი

2021-12-21 10:31 UTC, AnaRusadze commented on app/src/main/res/layout/zezva_fragment.xml
> +        android:id="@+id/view"
დააკონკრეტე რომელი ვიუა

2021-12-21 10:31 UTC, AnaRusadze commented on app/src/main/res/layout/zezva_fragment.xml
> +        android:backgroundTint="#7FB3DC"
ფერი

2021-12-21 10:31 UTC, AnaRusadze commented on app/src/main/res/layout/zezva_fragment.xml
> +    android:background="#25314A">
ფერი

2021-12-21 10:31 UTC, AnaRusadze commented on app/src/main/res/layout/zezva_fragment.xml
> +        android:textColorHint="#C8C8C8"
ფერები

2021-12-21 10:31 UTC, AnaRusadze commented on app/src/main/res/layout/zezva_fragment.xml
> +
ctrl alt l

2021-12-21 10:39 UTC, GiorgiMamagulashvili16 approved these changes

2021-12-21 10:39 UTC, GiorgiMamagulashvili16 commented on app/src/main/res/drawable/other_user_message.xml
> +        android:endColor="#475D8C"
ფერებში გაიტანე :დ

2021-12-21 10:39 UTC, GiorgiMamagulashvili16 commented on app/src/main/res/drawable/user_message_item.xml
> +        android:endColor="#7FB3DC"
ფერებში

2021-12-22 06:42 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/layout/other_user_message_layout.xml
> +<androidx.appcompat.widget.LinearLayoutCompat xmlns:android="http://schemas.android.com/apk/res/android"
თუ იმას გულისხმობ, რომ ორი ლეაიაუთი არ მქონდეს, ტექსტს ბექგრაუნდი აქვს, ხოლო მის დაბლა გაგზავნის თარიღს არა. თვითონ ტექსტვიუს რომ მივცე ეგეთი ბექგრაუნდი არ ჩაჯდება დიზაინში. ლინეარ ლეიაუთში კიდე იმიტომ მაქვს ჩასმული, რომ არაა მზიმე კონტეინერი, ვაფშე ახლა დავფიქრდი და თვითონ მესიჯი სადაც ჩანს ეგეთ ლინეარით უნდა მექნა :დ

2021-12-22 06:45 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/layout/zezva_fragment.xml
> +        android:id="@+id/view"
უბრალოდ ზოლია დიზაინიდან

2021-12-22 06:50 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/drawable/user_message_item.xml
> +        android:endColor="#7FB3DC"
done

2021-12-22 06:50 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/layout/zezva_fragment.xml
> +
done

2021-12-22 06:50 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/layout/zezva_fragment.xml
> +        android:textColorHint="#C8C8C8"
done

2021-12-22 06:50 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/layout/zezva_fragment.xml
> +    android:background="#25314A">
done

2021-12-22 06:51 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/layout/zezva_fragment.xml
> +        android:backgroundTint="#7FB3DC"
done

2021-12-22 06:51 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/layout/other_user_message_layout.xml
> +            tools:text="მზია მზია მზია"
done

2021-12-22 06:51 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/chat/ZezvaFragment.kt
> +class ZezvaFragment : Fragment() {
yep :3

2021-12-22 10:37 UTC, giorgiqemoklidze approved these changes

2022-01-11 15:05 UTC, merged